<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE AudioChannelLayouts
[
<!ELEMENT AudioChannelLayouts (LayoutCategory)*>
<!ELEMENT LayoutCategory (layout)*>
<!ATTLIST LayoutCategory ChannelValence CDATA #REQUIRED>
<!ELEMENT layout (name, channel_valence, item*)>
<!ELEMENT item (name, channel_map?, routing_map?)>
<!ELEMENT channel_map (channel)*>
<!ELEMENT routing_map (routing)*>
<!ELEMENT channel_valence ANY>
<!ELEMENT channel (#PCDATA)>
<!ELEMENT routing (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name localizable (true|false) "false">
<!ENTITY % routingString "( kAudioChannelLabel_Left | kAudioChannelLabel_Right | kAudioChannelLabel_Center | kAudioChannelLabel_LFEScreen | kAudioChannelLabel_LeftSurround | kAudioChannelLabel_RightSurround )">
]>

	<!--This table defines the layout options available for audio channels configuration-->

	<!--	LOCALIZER'S NOTE!  The layout names in this file are localization keys that will be converted
	        into their localized form when first loaded by the App.  The layout name will show up
			in the the Channel Configuration - Channels popup.  The item name will be what components
			are named when created with one of the selections (and can be seen inside the collection).
			Please do not alter any other tag, nor use ampersands or any other non-XML-safe character.
	-->

<AudioChannelLayouts>
    <LayoutCategory ChannelValence="1">
        <layout>
            <name>Channels_1-Mono</name>
            <channel_valence>1</channel_valence>
            <item>
                <name>mono</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_1-Left</name>
            <channel_valence>1</channel_valence>
            <item>
                <name>left</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
                <routing_map>
                    <routing>left</routing>
                </routing_map>
            </item>
        </layout>
        <layout>
            <name>Channels_1-Right</name>
            <channel_valence>1</channel_valence>
            <item>
                <name>right</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
                <routing_map>
                    <routing>right</routing>
                </routing_map>
            </item>
        </layout>
        <layout>
            <name>Channels_1-Center</name>
            <channel_valence>1</channel_valence>
            <item>
                <name>center</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
                <routing_map>
                    <routing>center</routing>
                </routing_map>
            </item>
        </layout>
        <layout>
            <name>Channels_1-LFE</name>
            <channel_valence>1</channel_valence>
            <item>
                <name>lfe</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
                <routing_map>
                    <routing>lfe</routing>
                </routing_map>
            </item>
        </layout>
        <layout>
            <name>Channels_1-LeftSurround</name>
            <channel_valence>1</channel_valence>
            <item>
                <name>left surround</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
                <routing_map>
                    <routing>left_surround</routing>
                </routing_map>
            </item>
        </layout>
        <layout>
            <name>Channels_1-RightSurround</name>
            <channel_valence>1</channel_valence>
            <item>
                <name>right surround</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
                <routing_map>
                    <routing>right_surround</routing>
                </routing_map>
            </item>
        </layout>
    </LayoutCategory>
    <LayoutCategory ChannelValence="2">
        <layout>
            <name>Channels_2-DualMono</name>
            <channel_valence>2</channel_valence>
            <item>
                <name>mono 1</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 2</name>
                <channel_map>
                    <channel>1</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_2-Stereo</name>
            <channel_valence>2</channel_valence>
            <item>
                <name>stereo</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_2-ReverseStereo</name>
            <channel_valence>2</channel_valence>
            <item>
                <name>reverse stereo</name>
                <channel_map>
                    <channel>1</channel>
                    <channel>0</channel>
                </channel_map>
            </item>
        </layout>
    </LayoutCategory>
    <LayoutCategory ChannelValence="3">
        <layout>
            <name>Channels_3-ThreeMono</name>
            <channel_valence>3</channel_valence>
            <item>
                <name>mono 1</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 2</name>
                <channel_map>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 3</name>
                <channel_map>
                    <channel>2</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_3-LeftCenterRight</name>
            <channel_valence>3</channel_valence>
            <item>
                <name>left/right</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                </channel_map>
                <routing_map>
                    <routing>left</routing>
                    <routing>right</routing>
                </routing_map>
            </item>
            <item>
                <name>center</name>
                <channel_map>
                    <channel>2</channel>
                </channel_map>
                <routing_map>
                    <routing>center</routing>
                </routing_map>
            </item>
        </layout>
    </LayoutCategory>
    <LayoutCategory ChannelValence="4">
        <layout>
            <name>Channels_4-FourMono</name>
            <channel_valence>4</channel_valence>
            <item>
                <name>mono 1</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 2</name>
                <channel_map>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 3</name>
                <channel_map>
                    <channel>2</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 4</name>
                <channel_map>
                    <channel>3</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_4-TwoStereo</name>
            <channel_valence>4</channel_valence>
            <item>
                <name>stereo 1</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 2</name>
                <channel_map>
                    <channel>2</channel>
                    <channel>3</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_4-LeftRightCenterSurround</name>
            <channel_valence>4</channel_valence>
            <item>
                <name>left/right</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                </channel_map>
                <routing_map>
                    <routing>left</routing>
                    <routing>right</routing>
                </routing_map>
            </item>
            <item>
                <name>center</name>
                <channel_map>
                    <channel>2</channel>
                </channel_map>
                <routing_map>
                    <routing>center</routing>
                </routing_map>
            </item>
            <item>
                <name>surround</name>
                <channel_map>
                    <channel>3</channel>
                    <channel>3</channel>
                </channel_map>
                <routing_map>
                    <routing>left_surround</routing>
                    <routing>right_surround</routing>
                </routing_map>
            </item>
        </layout>
    </LayoutCategory>
    <LayoutCategory ChannelValence="5">
        <layout>
            <name>Channels_5-FiveMono</name>
            <channel_valence>5</channel_valence>
            <item>
                <name>mono 1</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 2</name>
                <channel_map>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 3</name>
                <channel_map>
                    <channel>2</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 4</name>
                <channel_map>
                    <channel>3</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 5</name>
                <channel_map>
                    <channel>4</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_5-Surround_5_0</name>
            <channel_valence>5</channel_valence>
            <item>
                <name>front l/r</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                </channel_map>
                <routing_map>
                    <routing>left</routing>
                    <routing>right</routing>
                </routing_map>
            </item>
            <item>
                <name>center</name>
                <channel_map>
                    <channel>2</channel>
                </channel_map>
                <routing_map>
                    <routing>center</routing>
                </routing_map>
            </item>
            <item>
                <name>surround ls/rs</name>
                <channel_map>
                    <channel>3</channel>
                    <channel>4</channel>
                </channel_map>
                <routing_map>
                    <routing>left_surround</routing>
                    <routing>right_surround</routing>
                </routing_map>
            </item>
        </layout>
    </LayoutCategory>
    <LayoutCategory ChannelValence="6">
        <layout>
            <name>Channels_6-SixMono</name>
            <channel_valence>6</channel_valence>
            <item>
                <name>mono 1</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 2</name>
                <channel_map>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 3</name>
                <channel_map>
                    <channel>2</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 4</name>
                <channel_map>
                    <channel>3</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 5</name>
                <channel_map>
                    <channel>4</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 6</name>
                <channel_map>
                    <channel>5</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_6-ThreeStereo</name>
            <channel_valence>6</channel_valence>
            <item>
                <name>stereo 1</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 2</name>
                <channel_map>
                    <channel>2</channel>
                    <channel>3</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 3</name>
                <channel_map>
                    <channel>4</channel>
                    <channel>5</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_6-Stereo_TwoMono_Stereo</name>
            <channel_valence>6</channel_valence>
            <item>
                <name>stereo 1</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 2</name>
                <channel_map>
                    <channel>2</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 3</name>
                <channel_map>
                    <channel>3</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 2</name>
                <channel_map>
                    <channel>4</channel>
                    <channel>5</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_6-TwoMono_TwoStereo</name>
            <channel_valence>6</channel_valence>
            <item>
                <name>mono 1</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 2</name>
                <channel_map>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 1</name>
                <channel_map>
                    <channel>2</channel>
                    <channel>3</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 2</name>
                <channel_map>
                    <channel>4</channel>
                    <channel>5</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_6-Surround_5_1</name>
            <channel_valence>6</channel_valence>
            <item>
                <name>surround</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                    <channel>2</channel>
                    <channel>3</channel>
                    <channel>4</channel>
                    <channel>5</channel>
                </channel_map>
            </item>
        </layout>
    </LayoutCategory>
    <LayoutCategory ChannelValence="7">
        <layout>
            <name>Channels_7-SevenMono</name>
            <channel_valence>7</channel_valence>
            <item>
                <name>mono 1</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 2</name>
                <channel_map>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 3</name>
                <channel_map>
                    <channel>2</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 4</name>
                <channel_map>
                    <channel>3</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 5</name>
                <channel_map>
                    <channel>4</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 6</name>
                <channel_map>
                    <channel>5</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 7</name>
                <channel_map>
                    <channel>6</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_7-Surround_6_1</name>
            <channel_valence>7</channel_valence>
            <item>
                <name>surround 5.1</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                    <channel>2</channel>
                    <channel>3</channel>
                    <channel>4</channel>
                    <channel>5</channel>
                </channel_map>
            </item>
            <item>
                <name>center back</name>
                <channel_map>
                    <channel>6</channel>
                    <channel>6</channel>
                </channel_map>
                <routing_map>
                    <routing>left_surround</routing>
                    <routing>right_surround</routing>
                </routing_map>
            </item>
        </layout>
    </LayoutCategory>
    <LayoutCategory ChannelValence="8">
        <layout>
            <name>Channels_8-EightMono</name>
            <channel_valence>8</channel_valence>
            <item>
                <name>mono 1</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 2</name>
                <channel_map>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 3</name>
                <channel_map>
                    <channel>2</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 4</name>
                <channel_map>
                    <channel>3</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 5</name>
                <channel_map>
                    <channel>4</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 6</name>
                <channel_map>
                    <channel>5</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 7</name>
                <channel_map>
                    <channel>6</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 8</name>
                <channel_map>
                    <channel>7</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_8-FourStereo</name>
            <channel_valence>8</channel_valence>
            <item>
                <name>stereo 1</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 2</name>
                <channel_map>
                    <channel>2</channel>
                    <channel>3</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 3</name>
                <channel_map>
                    <channel>4</channel>
                    <channel>5</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 4</name>
                <channel_map>
                    <channel>6</channel>
                    <channel>7</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_8-Surround_5_1_AndStereo</name>
            <channel_valence>8</channel_valence>
            <item>
                <name>surround</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                    <channel>2</channel>
                    <channel>3</channel>
                    <channel>4</channel>
                    <channel>5</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo</name>
                <channel_map>
                    <channel>6</channel>
                    <channel>7</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_8-Surround_7_1_AndStereo</name>
            <channel_valence>8</channel_valence>
            <item>
                <name>front l/r</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                </channel_map>
                <routing_map>
                    <routing>left</routing>
                    <routing>right</routing>
                </routing_map>
            </item>
            <item>
                <name>center</name>
                <channel_map>
                    <channel>2</channel>
                </channel_map>
                <routing_map>
                    <routing>center</routing>
                </routing_map>
            </item>
            <item>
                <name>lfe</name>
                <channel_map>
                    <channel>3</channel>
                </channel_map>
                <routing_map>
                    <routing>lfe</routing>
                </routing_map>
            </item>
            <item>
                <name>surround ls/rs</name>
                <channel_map>
                    <channel>4</channel>
                    <channel>5</channel>
                </channel_map>
                <routing_map>
                    <routing>left_surround</routing>
                    <routing>right_surround</routing>
                </routing_map>
            </item>
            <item>
                <name>back lb/rb</name>
                <channel_map>
                    <channel>6</channel>
                    <channel>7</channel>
                </channel_map>
                <routing_map>
                    <routing>left_surround</routing>
                    <routing>right_surround</routing>
                </routing_map>
            </item>
        </layout>
    </LayoutCategory>
    <LayoutCategory ChannelValence="12">
        <layout>
            <name>Channels_12-TwelveMono</name>
            <channel_valence>12</channel_valence>
            <item>
                <name>mono 1</name>
                <channel_map>
                    <channel>0</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 2</name>
                <channel_map>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 3</name>
                <channel_map>
                    <channel>2</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 4</name>
                <channel_map>
                    <channel>3</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 5</name>
                <channel_map>
                    <channel>4</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 6</name>
                <channel_map>
                    <channel>5</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 7</name>
                <channel_map>
                    <channel>6</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 8</name>
                <channel_map>
                    <channel>7</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 9</name>
                <channel_map>
                    <channel>8</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 10</name>
                <channel_map>
                    <channel>9</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 11</name>
                <channel_map>
                    <channel>10</channel>
                </channel_map>
            </item>
            <item>
                <name>mono 12</name>
                <channel_map>
                    <channel>11</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_12-SixStereo</name>
            <channel_valence>12</channel_valence>
            <item>
                <name>stereo 1</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 2</name>
                <channel_map>
                    <channel>2</channel>
                    <channel>3</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 3</name>
                <channel_map>
                    <channel>4</channel>
                    <channel>5</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 4</name>
                <channel_map>
                    <channel>6</channel>
                    <channel>7</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 5</name>
                <channel_map>
                    <channel>8</channel>
                    <channel>9</channel>
                </channel_map>
            </item>
            <item>
                <name>stereo 6</name>
                <channel_map>
                    <channel>10</channel>
                    <channel>11</channel>
                </channel_map>
            </item>
        </layout>
        <layout>
            <name>Channels_12-DualSurround_5_1</name>
            <channel_valence>12</channel_valence>
            <item>
                <name>surround 1</name>
                <channel_map>
                    <channel>0</channel>
                    <channel>1</channel>
                    <channel>2</channel>
                    <channel>3</channel>
                    <channel>4</channel>
                    <channel>5</channel>
                </channel_map>
            </item>
            <item>
                <name>surround 2</name>
                <channel_map>
                    <channel>6</channel>
                    <channel>7</channel>
                    <channel>8</channel>
                    <channel>9</channel>
                    <channel>10</channel>
                    <channel>11</channel>
                </channel_map>
            </item>
        </layout>
    </LayoutCategory>
</AudioChannelLayouts>